global:
  edition: ce
  hosts:
    domain: local
    gitlab:
      name: gitlab.local
  ingress:
    enabled: false
    class: traefik
    tls:
      enabled: true
  appConfig:
    external_url: "https://gitlab.local"
    object_store:
      enabled: false
    artifacts:
      enabled: false
    lfs:
      enabled: false
    uploads:
      enabled: false
    packages:
      enabled: false
    backups:
      object_store:
        enabled: false
  gitlab-runner:
    enabled: false

certmanager:
  enabled: false

prometheus:
  enabled: false

nginx-ingress:
  enabled: false

registry:
  enabled: false

gitlab-runner:
  enabled: false

# === Composants GitLab principaux ===
gitlab:
  kas:
    enabled: false
  gitlab-exporter:
    enabled: false
  gitlab-shell:
    enabled: false
  sidekiq:
    enabled: false
  toolbox:
    enabled: false

  gitaly:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi

  webservice:
    service:
      httpsPort: 8181
      https: true
      externalPort: 443
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 2Gi

redis:
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi

postgresql:
  primary:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 512Mi
certmanager-issuer:
  email: "admin@gitlab.local"