global:
  edition: ce
  hosts:
    domain: gitlab.local
  ingress:
    configureCertmanager: false
    class: traefik
    tls:
      enabled: false
  minio:
    enabled: false
  appConfig:
    object_store:
      enabled: false
    artifacts:
      enabled: false
    lfs:
      enabled: false
    uploads:
      enabled: false
    packages:
      enabled: false
    backups:
      object_store:
        enabled: false

# Désactive tout ce qui n’est pas indispensable
certmanager:
  enabled: false

nginx-ingress:
  enabled: false

prometheus:
  enabled: false

gitlab-runner:
  enabled: false

registry:
  enabled: false

# Composants GitLab principaux
gitlab:
  kas:
    enabled: false
  gitlab-exporter:
    enabled: false
  gitlab-shell:
    enabled: false
  sidekiq:
    enabled: false       # ⚠️ CI/CD inutile -> désactivé
  toolbox:
    enabled: false

  gitaly:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 256Mi

  webservice:
    minReplicas: 1
    maxReplicas: 1
    resources:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 2Gi

redis:
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi

postgresql:
  primary:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        memory: 512Mi
