apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: gitlab-headers
  namespace: gitlab
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Ssl: "on"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitlab
  namespace: gitlab
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`gitlab.local`)
      services:
        - name: gitlab-webservice-default
          port: 8181    # ✅ c’est ce port qu’utilise GitLab pour HTTPS interne
      middlewares:
        - name: gitlab-headers
  tls:
    certResolver: default   # ✅ sans le point à la fin

