Vagrant.configure("2") do |config|
  # Base image (Debian 12)
  config.vm.box = "debian/bookworm64"

  # Use VirtualBox explicitly
  config.vm.provider "virtualbox"

  # Common SSH options (passwordless via Vagrant's key by default)
  config.ssh.insert_key = true

  # ----- Server (controller) -----
  config.vm.define "ikaismouS" do |s|
    s.vm.hostname = "ikaismouS"
    s.vm.network "private_network", ip: "192.168.56.110"  # eth1
    s.vm.provider "virtualbox" do |vb|
      vb.name = "ikaismouS"
      vb.cpus = 2
      vb.memory = 4096
    end
    # Sync local manifests
    s.vm.synced_folder "confs", "/home/vagrant/confs"

    # Use external provision script
    s.vm.provision "shell", path: "scripts/provision.sh"

  end
end